services:
  orpheusdl:
    image: ghcr.io/theminecraftguyguru/orpheusdl-container:settings-json-format
    container_name: orpheusdl
    ports:
      - "8080:8080"
    volumes:
      - ./music:/data/music:rw
      - ./data:/data:rw
      - ./config:/orpheusdl/config:rw
      - ./modules:/orpheusdl/modules:rw
    restart: unless-stopped
