name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run lint and bytecode checks in Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            ghcr.io/library/python:3.11-slim \
            bash -lc "python -m pip install --upgrade pip ruff && ruff check . --exclude external && python -m compileall list_ui_server.py notifications.py tests"

  tests:
    name: Tests
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run pytest inside Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            ghcr.io/library/python:3.11-slim \
            bash -lc "python -m pip install --upgrade pip pytest requests && pytest tests --ignore=external"

  docker:
    name: Docker build
    runs-on: self-hosted
    needs: tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: orpheusdl:test
