name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install lint dependencies
        run: python3 -m pip install --upgrade pip ruff

      - name: Run ruff
        run: ruff check .

      - name: Verify Python bytecode compiles
        run: python3 -m compileall list_ui_server.py notifications.py tests

  tests:
    name: Tests
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest requests

      - name: Run pytest
        run: pytest

  docker:
    name: Docker build
    runs-on: self-hosted
    needs: tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: orpheusdl:test
