name: Publish Docker image

on:
  push:
    branches: [ "main", "settings.json-format" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU emulation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image tags
        id: metadata
        run: |
          tags="ghcr.io/theminecraftguyguru/orpheusdl-container:${GITHUB_SHA}"
          ref_name="${GITHUB_REF##*/}"

          if [ "${ref_name}" = "main" ]; then
            tags=$'ghcr.io/theminecraftguyguru/orpheusdl-container:latest\n'"${tags}"
          elif [ "${ref_name}" = "settings.json-format" ]; then
            tags=$'ghcr.io/theminecraftguyguru/orpheusdl-container:settings-json-format\n'"${tags}"
          fi

          {
            echo 'tags<<EOF'
            echo "${tags}"
            echo 'EOF'
          } >> "${GITHUB_OUTPUT}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.metadata.outputs.tags }}
